version: "3"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file: ./server/.env
    depends_on:
      - mongo
  client:
    build: ./client
    ports:
      - "3000:80"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
